name: Build Realworld App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Build
        run: cd java-realworld-app && mvn -B install
      - name: Build image
        run: cd java-realworld-app && mvn -B spring-boot:build-image
      - name: Build native image
        run: cd java-realworld-app && mvn -B -Pnative spring-boot:build-image
      - name: Push image to ghcr.io
        if: ${{ github.event_name != 'pull_request'}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker push ghcr.io/derkoe/azure-java-realworld-app:latest
          docker push ghcr.io/derkoe/azure-java-realworld-app:native